### ISSUE TITLE
Flapping Test

### ISSUE THREAD

**Issue by paulosman** [honeycombio/beeline-java#39]
```
[ERROR] Failures: 
[ERROR]   BeelineServletFilterTest.testErroring:250 
mockTransport.submit(<Capturing argument>);
Wanted 2 times:
-> at io.honeycomb.beeline.tracing.propagation.BeelineServletFilterTest.testErroring(BeelineServletFilterTest.java:250)
But was 1 time:
-> at io.honeycomb.libhoney.HoneyClient.sendEventPresampled(HoneyClient.java:248)
```

**Comment by vreynolds** [comment]
Haven't observed in recent builds
