### ISSUE TITLE
No serializer found for class org.postgresql.core.v3.replication.V3ReplicationProtocol

### ISSUE THREAD

**Issue by 2ndalpha** [honeycombio/beeline-java#76]
`beeline-spring-boot-starter` version `1.3.0`

```
io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.postgresql.core.v3.replication.V3ReplicationProtocol and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0]->io.honeycomb.libhoney.transport.batch.impl.HoneycombBatchConsumer$BatchRequestElement["data"]->java.util.HashMap["db.query_params"]->java.util.ArrayList[0]->java.util.HashMap["3"]->org.postgresql.jdbc.PgArray["resultSet"]->org.postgresql.jdbc.PgResultSet["statement"]->org.postgresql.jdbc.PgStatement["connection"]->org.postgresql.jdbc.PgConnection["queryExecutor"]->org.postgresql.core.v3.QueryExecutorImpl["replicationProtocol"])
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:782)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:782)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:171)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:400)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1392)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at io.honeycomb.libhoney.shaded.com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1017)
	at io.honeycomb.libhoney.transport.json.BatchRequestSerializer.serialize(BatchRequestSerializer.java:24)
	at io.honeycomb.libhoney.transport.json.BatchRequestSerializer.serialize(BatchRequestSerializer.java:15)
	at io.honeycomb.libhoney.transport.batch.impl.HoneycombBatchConsumer.consume(HoneycombBatchConsumer.java:111)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.submitBatch(DefaultBatcher.java:217)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.handleTimeoutTriggers(DefaultBatcher.java:236)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher.access$400(DefaultBatcher.java:36)
	at io.honeycomb.libhoney.transport.batch.impl.DefaultBatcher$BatchingWorker.run(DefaultBatcher.java:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by MikeGoldsmith** [comment]
Hi @2ndalpha

The FasterXML dependency was not been updated as part of the `1.3.0` release and has been consistent for a long time. 

I have a couple of follow-up questions if you can help:
- Did you upgrade the beeline in an existing application or are you starting fresh?
- Does your application use FasterXml in it's dependency chain anywhere?
- Please can you share your pom.xml / gradle file, or even better would be a sample app showing the problem.

Thanks!

**Comment by JamieDanielson** [comment]
We are closing this issue as there has been no recent activity. Feel free to request a re-open if this is still relevant.
